import type { Metadata } from "next";
import { Navigation } from "@/components/navigation";
import { Footer } from "@/components/footer";
import { Badge } from "@/components/ui/badge";

export const metadata: Metadata = {
  title: "Terms of Service | Tinzwave",
  description: "The terms governing your use of the Tinzwave website and services.",
};

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-black text-white">
      <Navigation />

      <section className="relative py-28 overflow-hidden">
        <div className="absolute inset-0 bg-gradient-to-br from-[#03005F]/40 via-black to-black" />
        <div className="container mx-auto px-4 relative z-10">
          <div className="max-w-3xl mx-auto text-center">
            <Badge className="mb-4 px-4 py-1.5 border border-white/20 bg-white/5 text-white/70 font-mono text-xs tracking-widest">
              LEGAL
            </Badge>
            <h1 className="text-4xl md:text-6xl font-bold tracking-tight text-white">
              Terms of Service
            </h1>
            <p className="mt-4 text-white/40 text-sm">Last updated: August 2, 2026</p>
          </div>
        </div>
      </section>

      <section className="py-16">
        <div className="container mx-auto px-4">
          <div className="max-w-3xl mx-auto space-y-10 text-white/60 leading-relaxed">
            <p className="text-white/50 text-sm border border-white/10 bg-white/5 rounded-xl p-4">
              These are general-purpose terms and are not a substitute for advice from a qualified lawyer. If you
              need this document to meet specific legal or regulatory requirements, please have it reviewed by legal
              counsel before relying on it.
            </p>

            <div>
              <h2 className="text-2xl font-bold text-white mb-3">Acceptance of Terms</h2>
              <p>
                By accessing or using the Tinzwave Technologies ("Tinzwave", "we", "us") website, you agree to be
                bound by these Terms of Service. If you do not agree, please do not use this website.
              </p>
            </div>

            <div>
              <h2 className="text-2xl font-bold text-white mb-3">Our Services</h2>
              <p>
                Tinzwave operates across three divisions: Tinzwave AI Academy (technology training and courses),
                Tinzwave Labs (software and AI development services), and Tinzwave Workspace (co-working and event
                space). Descriptions, pricing, and availability of courses and services on this website are subject
                to change without notice.
              </p>
            </div>

            <div>
              <h2 className="text-2xl font-bold text-white mb-3">Course Enrollment</h2>
              <p>
                Enrolling in a course requires agreeing to the specific pricing, schedule, and payment terms
                communicated to you at the point of registration. Fees, refund conditions, and cohort dates are
                confirmed directly with our team via WhatsApp, email, or in person and are not automatically
                generated by this website.
              </p>
            </div>

            <div>
              <h2 className="text-2xl font-bold text-white mb-3">Intellectual Property</h2>
              <p>
                All content on this website — including text, graphics, logos, and course materials — is the
                property of Tinzwave or its licensors and is protected by applicable intellectual property laws. You
                may not reproduce, distribute, or create derivative works from this content without our written
                permission.
              </p>
            </div>

            <div>
              <h2 className="text-2xl font-bold text-white mb-3">Acceptable Use</h2>
              <p>
                You agree not to use this website for any unlawful purpose, to attempt unauthorized access to our
                systems, or to interfere with the site's normal operation.
              </p>
            </div>

            <div>
              <h2 className="text-2xl font-bold text-white mb-3">Third-Party Links</h2>
              <p>
                This website links to third-party services including WhatsApp, Google Maps, and social media
                platforms. We are not responsible for the content or practices of these external sites.
              </p>
            </div>

            <div>
              <h2 className="text-2xl font-bold text-white mb-3">Disclaimer & Limitation of Liability</h2>
              <p>
                This website and its content are provided "as is" without warranties of any kind. To the fullest
                extent permitted by law, Tinzwave shall not be liable for any indirect, incidental, or consequential
                damages arising from your use of this website.
              </p>
            </div>

            <div>
              <h2 className="text-2xl font-bold text-white mb-3">Governing Law</h2>
              <p>These terms are governed by the laws of the Federal Republic of Nigeria.</p>
            </div>

            <div>
              <h2 className="text-2xl font-bold text-white mb-3">Changes to These Terms</h2>
              <p>
                We may update these terms from time to time. Continued use of the website after changes are posted
                constitutes acceptance of the revised terms.
              </p>
            </div>

            <div>
              <h2 className="text-2xl font-bold text-white mb-3">Contact Us</h2>
              <p>
                Questions about these terms can be sent to{" "}
                <a href="mailto:info@tinzwave.com" className="text-indigo-400 hover:text-indigo-300 transition">
                  info@tinzwave.com
                </a>{" "}
                or by visiting us at E6 Adeniran Ogunsanya Shoprite Mall, Surulere, Lagos, Nigeria.
              </p>
            </div>
          </div>
        </div>
      </section>

      <Footer />
    </div>
  );
}
