export interface Course {
  id: string
  title: string
  slug: string
  category: string
  duration: string
  price: string
  blackFridayPrice: string
  description: string
  overview: string
  whatYouLearn: string[]
  tools: string[]
  whoShouldEnroll: string[]
  mode: string[]
}

export const courses: Course[] = [
  {
    id: "1",
    title: "Frontend Development",
    slug: "frontend-development",
    category: "Web Development",
    duration: "2 months",
    price: "₦100,000",
    blackFridayPrice: "₦80,000",
    description: "Master modern frontend development with HTML, CSS, JavaScript, and React",
    overview:
      "Learn to build beautiful, responsive, and interactive user interfaces using the latest frontend technologies. This course covers everything from HTML/CSS fundamentals to advanced React concepts.",
    whatYouLearn: [
      "HTML5 and semantic markup",
      "CSS3 and responsive design",
      "JavaScript ES6+ fundamentals",
      "React.js and component-based architecture",
      "State management with hooks",
      "API integration",
      "Version control with Git",
      "Deployment and hosting",
    ],
    tools: ["HTML", "CSS", "JavaScript", "React", "Git", "VS Code"],
    whoShouldEnroll: [
      "Beginners interested in web development",
      "Designers wanting to code their designs",
      "Career switchers entering tech",
      "Anyone wanting to build websites",
    ],
    mode: ["Physical", "Virtual"],
  },
  {
    id: "2",
    title: "Backend Development",
    slug: "backend-development",
    category: "Web Development",
    duration: "2 months",
    price: "₦100,000",
    blackFridayPrice: "₦80,000",
    description: "Build robust server-side applications with Node.js, Express.js, and APIs",
    overview:
      "Master backend development and learn to build scalable server applications, RESTful APIs, and manage databases. Perfect for those who want to handle the server side of web applications.",
    whatYouLearn: [
      "Node.js fundamentals",
      "Express.js framework",
      "RESTful API design",
      "Database management (SQL & NoSQL)",
      "Authentication and authorization",
      "API security best practices",
      "Server deployment",
      "Testing and debugging",
    ],
    tools: ["Node.js", "Express.js", "MongoDB", "PostgreSQL", "Postman", "Git"],
    whoShouldEnroll: [
      "Frontend developers wanting full-stack skills",
      "Beginners interested in server-side development",
      "Developers wanting to build APIs",
      "Tech enthusiasts learning backend",
    ],
    mode: ["Physical", "Virtual"],
  },
  {
    id: "3",
    title: "Fullstack Development",
    slug: "fullstack-development",
    category: "Web Development",
    duration: "4 months",
    price: "₦200,000",
    blackFridayPrice: "₦160,000",
    description: "Complete frontend and backend development with APIs and databases",
    overview:
      "Become a complete fullstack developer by mastering both frontend and backend technologies. Build complete web applications from scratch with React, Node.js, databases, and APIs.",
    whatYouLearn: [
      "Frontend development (HTML, CSS, JavaScript, React)",
      "Backend development (Node.js, Express.js)",
      "Database design and management",
      "RESTful API development",
      "Authentication systems",
      "State management",
      "Full application deployment",
      "Project architecture",
    ],
    tools: ["React", "Node.js", "Express.js", "MongoDB", "PostgreSQL", "Git", "AWS/Vercel"],
    whoShouldEnroll: [
      "Aspiring software developers",
      "Career switchers to tech",
      "Entrepreneurs building their own products",
      "Anyone wanting comprehensive web dev skills",
    ],
    mode: ["Physical", "Virtual"],
  },
  {
    id: "4",
    title: "UI/UX Design",
    slug: "ui-ux-design",
    category: "Design",
    duration: "2 months",
    price: "₦100,000",
    blackFridayPrice: "₦80,000",
    description: "Design beautiful interfaces using Figma, wireframing, and prototyping",
    overview:
      "Learn to design user-centered digital experiences that are both beautiful and functional. Master industry-standard design tools and methodologies used by top tech companies.",
    whatYouLearn: [
      "UI/UX design principles",
      "User research and personas",
      "Wireframing and prototyping",
      "Figma mastery",
      "Design systems",
      "Responsive design",
      "Usability testing",
      "Portfolio development",
    ],
    tools: ["Figma", "Adobe XD", "Sketch", "InVision", "Miro"],
    whoShouldEnroll: [
      "Aspiring UI/UX designers",
      "Graphic designers transitioning to digital",
      "Developers wanting design skills",
      "Product managers",
    ],
    mode: ["Physical", "Virtual"],
  },
  {
    id: "5",
    title: "Product Management",
    slug: "product-management",
    category: "Management",
    duration: "2 months",
    price: "₦100,000",
    blackFridayPrice: "₦80,000",
    description: "Master product lifecycle, user personas, and strategy",
    overview:
      "Learn to manage products from conception to launch. Understand user needs, define product strategy, work with development teams, and drive product success.",
    whatYouLearn: [
      "Product lifecycle management",
      "User research and personas",
      "Product roadmapping",
      "Agile and Scrum methodologies",
      "Stakeholder management",
      "Data-driven decision making",
      "Go-to-market strategies",
      "Metrics and KPIs",
    ],
    tools: ["Jira", "Trello", "Miro", "Google Analytics", "Figma"],
    whoShouldEnroll: [
      "Aspiring product managers",
      "Business analysts",
      "Entrepreneurs",
      "Anyone wanting to understand product development",
    ],
    mode: ["Physical", "Virtual"],
  },
  {
    id: "6",
    title: "Project Management",
    slug: "project-management",
    category: "Management",
    duration: "2 months",
    price: "₦100,000",
    blackFridayPrice: "₦80,000",
    description: "Learn Agile, Scrum, and master tools like Jira and Trello",
    overview:
      "Master the art of project management using Agile and Scrum methodologies. Learn to plan, execute, and deliver projects on time and within budget.",
    whatYouLearn: [
      "Project management fundamentals",
      "Agile and Scrum frameworks",
      "Sprint planning and execution",
      "Team management",
      "Risk management",
      "Stakeholder communication",
      "Project documentation",
      "Jira and Trello mastery",
    ],
    tools: ["Jira", "Trello", "Asana", "Microsoft Project", "Slack"],
    whoShouldEnroll: ["Aspiring project managers", "Team leads", "Business professionals", "Anyone managing projects"],
    mode: ["Physical", "Virtual"],
  },
  {
    id: "7",
    title: "Digital Marketing",
    slug: "digital-marketing-course",
    category: "Marketing",
    duration: "2 months",
    price: "₦100,000",
    blackFridayPrice: "₦80,000",
    description: "Master SEO, content marketing, ads, and analytics",
    overview:
      "Learn to create and execute effective digital marketing campaigns that drive results. Master SEO, social media, content marketing, and paid advertising.",
    whatYouLearn: [
      "Digital marketing strategy",
      "Search Engine Optimization (SEO)",
      "Social media marketing",
      "Content marketing",
      "Google Ads and Facebook Ads",
      "Email marketing",
      "Analytics and reporting",
      "Conversion optimization",
    ],
    tools: ["Google Analytics", "Google Ads", "Facebook Ads Manager", "SEMrush", "Mailchimp"],
    whoShouldEnroll: [
      "Aspiring digital marketers",
      "Business owners",
      "Marketing professionals",
      "Social media managers",
    ],
    mode: ["Physical", "Virtual"],
  },
  {
    id: "9",
    title: "AI Engineering",
    slug: "ai-engineering",
    category: "Artificial Intelligence",
    duration: "3 months",
    price: "₦300,000",
    blackFridayPrice: "₦240,000",
    description: "Master neural networks, NLP, computer vision, and AI deployment",
    overview:
      "Dive deep into artificial intelligence and machine learning. Learn to build intelligent systems using neural networks, natural language processing, and computer vision.",
    whatYouLearn: [
      "Machine learning fundamentals",
      "Neural networks and deep learning",
      "Natural Language Processing (NLP)",
      "Computer vision",
      "TensorFlow and PyTorch",
      "Model deployment",
      "AI ethics",
      "Real-world AI projects",
    ],
    tools: ["Python", "TensorFlow", "PyTorch", "Keras", "Jupyter Notebook", "Google Colab"],
    whoShouldEnroll: [
      "Software developers",
      "Data scientists",
      "Tech professionals wanting AI skills",
      "Students interested in AI",
    ],
    mode: ["Physical", "Virtual"],
  },
  {
    id: "10",
    title: "Fullstack Software Engineering",
    slug: "fullstack-software-engineering",
    category: "Software Engineering",
    duration: "3 months",
    price: "₦200,000",
    blackFridayPrice: "₦160,000",
    description: "Advanced software architectures and microservices",
    overview:
      "Master advanced software engineering concepts and build enterprise-grade applications. Learn system design, microservices, DevOps, and industry best practices.",
    whatYouLearn: [
      "Advanced architecture patterns",
      "Microservices design",
      "System design",
      "Cloud computing",
      "Containerization (Docker)",
      "CI/CD pipelines",
      "Testing strategies",
      "Performance optimization",
    ],
    tools: ["Node.js", "React", "Docker", "Kubernetes", "AWS", "Git", "Jenkins"],
    whoShouldEnroll: [
      "Experienced developers",
      "Software engineers",
      "Full-stack developers wanting to level up",
      "Tech leads",
    ],
    mode: ["Physical", "Virtual"],
  },
  {
    id: "12",
    title: "Data Analysis",
    slug: "data-analysis",
    category: "Data Science",
    duration: "2 months",
    price: "₦200,000",
    blackFridayPrice: "₦160,000",
    description: "Master Excel, SQL, Power BI, and create insightful dashboards",
    overview:
      "Learn to analyze data and create meaningful insights using industry-standard tools. Perfect for those who want to make data-driven decisions.",
    whatYouLearn: [
      "Data analysis fundamentals",
      "Excel advanced techniques",
      "SQL for data querying",
      "Power BI dashboard creation",
      "Data visualization best practices",
      "Statistical analysis",
      "Data cleaning and preparation",
      "Business intelligence",
    ],
    tools: ["Excel", "SQL", "Power BI", "Tableau", "Python (Pandas)"],
    whoShouldEnroll: ["Business analysts", "Data enthusiasts", "Business professionals", "Anyone wanting data skills"],
    mode: ["Physical", "Virtual"],
  },
]
